# Generated by Django 4.0.4 on 2022-05-09 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_photocomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photocomment',
            old_name='photo_id',
            new_name='photo',
        ),
    ]
